---
title: "Bassingbourn Xmas Trail 2023"
format: html
editor: visual
---

```{r,warning=F,message=F,echo=F}
library(tidyverse)
library(ggmap)
library(jsonlite)  # Load the jsonlite package
library(leaflet)
library(DT)
library(knitr)
library(kableExtra)

###################################
# Add list of addresses here
###################################
df<-tibble(
  address = c(
    "49 Brook Rd, Bassingbourn, UK",
    "15 High St, Bassingbourn, UK",
    "27 High St, Bassingbourn, UK",
    "12 High St, Bassingbourn, UK",
    "38 High St, Bassingbourn, UK",
    "13 Causeway, Bassingbourn, UK",
    "24 Mill Lane, Bassingbourn, UK",
    "24a Old North Road, Bassingbourn, UK",
    "14 Park View, Bassingbourn, UK",
    "22 Park View, Bassingbourn, UK",
    "88 Spring Lane, Bassingbourn, UK",
    "24 Windmill Close, Bassingbourn, UK",
    "13 Windmill Close, Bassingbourn, UK",
    "2 Tanyard, Bassingbourn, UK",
    "2 Walnut Tree Close, Bassingbourn, UK",
    "45 Elm Tree Drive, Bassingbourn, UK"
  ),
  number = c(1,2,3,10,14,4,5,6,13,15,16,7,12,8,9,11)
  )

###################################
# Create a custom geocoding function which uses a free service from osm
###################################

custom_geocode <- function(address) {
  url <- paste0("https://nominatim.openstreetmap.org/search?format=json&limit=1&q=", URLencode(address))
  result <- fromJSON(url)
  if (length(result) > 0) {
    return(data.frame(
      lat = as.numeric(result$lat),
      lon = as.numeric(result$lon)
    ))
  } else {
    return(data.frame(lat = NA, lon = NA))
  }
}

###################################
# Get the geocodes for the addresses and bind to original tibble
###################################

geocoded_data <- as_tibble(t(sapply(df$address, custom_geocode)))

df<-cbind(df,geocoded_data) %>% 
  mutate(lat = as.numeric(lat),
         lon = as.numeric(lon),
         
         )

###################################
# Draw a leaflet map
###################################

# Create a Leaflet map with snowflake markers using numbers as labels
map <- leaflet(df) %>%
    addTiles() %>% 
  addMarkers(
    icon = makeIcon(iconUrl = "https://images.vexels.com/media/users/3/128626/isolated/preview/f30fc1dda925b2ceeaef55263ef85b8a-red-xmas-snowflake-by-vexels.png", 
                    iconWidth = 25, iconHeight = 25),
    label = ~as.character(df$address),
    labelOptions = labelOptions(
      noHide = F),)  # Permanent labels


# Display the map


```

## Map

```{r,echo=F}
map
```

## Addresses

```{r,echo=F}
df <- df %>% arrange(as.numeric(number))

kable(df, "html") %>%
  kable_styling("striped", full_width = FALSE) %>%
  scroll_box(width = "100%", height = "300px")  # Optional: Add a scroll box if needed
```
